# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PullViewController-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PullViewController-Swift

  pod 'SGPagingView', '~> 1.6.0'
  pod 'MJRefresh'
  pod 'SnapKit'

  target 'PullViewController-SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PullViewController-SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
