# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PullNewController' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PullNewController

  pod 'SGPagingView', '~> 1.6.0'
  pod 'MJRefresh'
  pod 'Masonry'
  pod 'FXBlurView'
  pod 'GPUImage'

  target 'PullNewControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PullNewControllerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
